workflows:
  android-workflow:
    name: Android Workflow
    max_build_duration: 60
    environment:
      node: 18
    scripts:
      - name: Install dependencies
        script: npm install
      - name: Build for Android
        script: |
          cd android
          chmod +x gradlew
          ./gradlew assembleDebug
    artifacts:
      - android/app/build/outputs/apk/debug/app-debug.apk
